[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
soluck_roulette_program = "EesrPZXx8b6hwLcAMBFtA7RZHyuvs7oFshBoDiK23VBk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
